---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: hw-type-ran-subscription
  namespace: hw-type-ran-subscriptions
spec:
  type: GitHub
  pathname: github.com/yrobla/ztp-ran-manifests
