---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: sample-site-du-subscription
  namespace: sample-site-du-subscription
spec:
  type: GitHub
  pathname: https://github.com/redhat-ztp/ztp-ran-manifests
