---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: profile-ran-subscription
  namespace: profile-ran-subscriptions
spec:
  type: GitHub
  pathname: https://github.com/redhat-ztp/ztp-ran-manifests
